openapi: 3.0.1
info:
  title: ThymeSave | Funnel
  version: 0.0.1
  contact:
    name: ThymeSave
    url: https://github.com/thymesave

paths:
  /:
    get:
      description: Funnel information and OIDC config
      responses:
        200:
          description: API is reachable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiInfo'
  /services/couchdb/*:
    parameters:
      - name: path
        in: path
        description: CouchDB request path
        schema:
          type: string
          format: path
    get:
      description: CouchDB Proxy
      responses:
        200:
          description: request completed successfully
        201:
          description: document is created
        202:
          description: request is accepted
        404:
          description: server is unable to find the requested content
        405:
          description: HTTP request type used is invalid
        409:
          description: there is any update conflict
        418:
          description: path is not routed to couchdb
        401:
          description: user is not authorized
        403:
          description: user is missing required permissions
        500:
          description: the data sent in the request is invalid
        502:
          description: upstream is unreachable
    post:
      description: CouchDB Proxy
      responses:
        200:
          description: request completed successfully
        201:
          description: document is created
        202:
          description: request is accepted
        404:
          description: server is unable to find the requested content
        405:
          description: HTTP request type used is invalid
        409:
          description: there is any update conflict
        418:
          description: path is not routed to couchdb
        401:
          description: user is not authorized
        403:
          description: user is missing required permissions
        500:
          description: the data sent in the request is invalid
        502:
          description: upstream is unreachable
    put:
      description: CouchDB Proxy
      responses:
        200:
          description: request completed successfully
        201:
          description: document is created
        202:
          description: request is accepted
        404:
          description: server is unable to find the requested content
        405:
          description: HTTP request type used is invalid
        409:
          description: there is any update conflict
        418:
          description: path is not routed to couchdb
        401:
          description: user is not authorized
        403:
          description: user is missing required permissions
        500:
          description: the data sent in the request is invalid
        502:
          description: upstream is unreachable
    delete:
      description: CouchDB Proxy
      responses:
        200:
          description: request completed successfully
        201:
          description: document is created
        202:
          description: request is accepted
        404:
          description: server is unable to find the requested content
        405:
          description: HTTP request type used is invalid
        409:
          description: there is any update conflict
        418:
          description: path is not routed to couchdb
        401:
          description: user is not authorized
        403:
          description: user is missing required permissions
        500:
          description: the data sent in the request is invalid
        502:
          description: upstream is unreachable
    options:
      description: CouchDB Proxy Preflight
      responses:
        200:
          description: satisfy browser requirements
  /metrics:
    get:
      description: Prometheus metrics
      responses:
        200:
          description: Prometheus text
          content:
            text/plain; version=0.0.4; charset=utf-8:
              schema:
                description: "Prometheus metric format"
  /self-service/db:
    put:
      description: Initialize database for user
      responses:
        200:
          description: Database is already initialized and has not been updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SelfServiceDB'
        201:
          description: Database has been initialized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SelfServiceDB'


components:
  schemas:
    ApiInfo:
      description: API info and webapp config
      properties:
        funnel:
          description: Information about funnel instance
          type: object
          properties:
            version:
              type: string
              description: Semantic version
            gitSha:
              type: string
              description: Git short sha of the last commit used for building
            buildTime:
              type: string
              description: Timestamp of build
        oidc:
          description: OIDC related configuration
          type: object
          properties:
            clientId:
              type: string
              description: OAuth2 Client ID
            configUrl:
              type: string
              description: OIDC configuration path
            issuerUrl:
              type: string
              description: Issuer URL for OIDC
            scopes:
              type: array
              description: Scopes to request for JWT
              items:
                type: string
            usernameClaim:
              type: string
              description: JWT claim to use as username to display
    SelfServiceDB:
      description: Response for self service database intialization
      properties:
        dbName:
          type: string
          description: Name of the database to use
